version: "3"
services:
        app:
            container_name: avcon-node-simple
            image: avimg-node-simple       
            restart: always
            build: .
            env_file: ./.env
            ports:
              - $NODE_LOCAL_PORT:$NODE_DOCKER_PORT  