version: "3"
services:
        app:
            container_name: avcon-kubernete-node-simple
            image: avimg-kubernete-node-simple       
            restart: always
            build: .
            env_file: ./.env
            ports:
              - $NODE_LOCAL_PORT:$NODE_DOCKER_PORT      
        